### ISSUE TITLE
Add automatic changelog

### ISSUE THREAD

**Issue by anthuanvasquez** [minnek-digital-studio/cominnek#16]
Add automatic changelog to the repo using a file like this: `.cominnekrc`. To read all the related settings.

.cominnekrc
```json
{
    "project-key": "JIRA-KEY"
}

```

Something similar to https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli

**Comment by isaacismaelx14** [comment]
## To do:

Add all tickets version to the release commit: 

commit body:
```txt
closed: TICKET-1, TICKET-2 ... 
```
